#include "CardList.h"

#include <QDir>
#include <QFile>
#include <QTextStream>

void CardList::ReadCSV() {
    QString path = QDir::currentPath()+"/DominionCardList.csv";
    // checks if file exists
    if (path.isEmpty() == false) {
        QFile file(path);   // initializes file
        // checks if file can be opened
        if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
            return;
        }
        file.open(QIODevice::ReadOnly); // opens file
        QTextStream in(&file);  // sets up textstream iterator
        QString line;
        QList<QString> line_parts;
        int line_num = 0;
        // since some cards have rules with multiple lines, this solution
        // is needed to read over multiple lines
        Card card;
        while (in.atEnd() == false) {
            line = in.readLine(0);
            if (line_num > 0) {// && line.startsWith('"')) {    // ensures it starts at actual data
                line_parts = line.split("\",\"", QString::SkipEmptyParts);
                for (int i = 0; i<line_parts.size(); i++) {
                    line_parts[i].remove("\"");
                }
                if (line_parts.size() > 1) {    // if line contains basic info
                    card.name = line_parts[0];
                    card.FixName(); // create variable name
                    card.set = line_parts[1];
                    card.type = line_parts[2];
                    card.cost = line_parts[3];
                    card.rules = line_parts[4];
                }
                else {  // if line is an extended description
                    card.rules.append(" "+line.remove("\""));
                }
                // write to database
                hash.insert(card.name, card);
            }
            line_num++;
        }
        file.close();
    }
    names = hash.keys();
    names.sort();
}

void CardList::WriteCPP() {
    QString output = QDir::currentPath()+"/DominionCardList.txt";
    // if file exists, delete it to prevent old data from being present
    if (QFile::exists(output) == true) {
        QFile::remove(output);
    }
    QFile file(output);
    file.open(QIODevice::ReadWrite);
    QTextStream out(&file);
    QString open = "\(QString(\"";
    QString close = "\"));";
    QString sep = "\"),QString(\"";

    // text document output begins here
    out << "Card ";
    for (int i = 0; i < hash.size(); i++) {
        Card card = hash.value(names[i]);
        if (i == 0) {
            out << card.name_variable;
        }
        else {
        out << ", "+card.name_variable;
        }
    }
    out << ";" << endl;
    for (int i = 0; i < hash.size(); i++) {
        Card card = hash.value(names[i]);
        out << card.name_variable+".Set"+open+card.name+sep+card.set+sep+
               card.cost+sep+card.type+sep+card.rules+close;
        out << " "+card.name_variable+".FixName();";
        out << endl;
    }
}

CardList::CardList() {
    // auto-generated by text output of WriteCPP() above
    // must copy the DominionCardList.txt output to this
    AbandonedMine.Set(QString("AbandonedMine"),QString("Dark Ages"),QString("$0"),QString("Action - Ruins"),QString("+1 Coin,,,,,,")); AbandonedMine.FixName();
    Adventurer.Set(QString("Adventurer"),QString("Base"),QString("$6"),QString("Action"),QString("Reveal cards from your deck until you reveal 2 Treasure cards. Put those Treasure cards into your hand and discard the other revealed cards.,,,,,,")); Adventurer.FixName();
    Advisor.Set(QString("Advisor"),QString("Guilds"),QString("$4"),QString("Action"),QString("+1 Action. Reveal the top 3 cards of your deck. The player to your left chooses one of them. Discard that card. Put the other cards into your hand.,,,,,,")); Advisor.FixName();
    Alchemist.Set(QString("Alchemist"),QString("Alchemy"),QString("$3 1P"),QString("Action"),QString("+2 Cards +1 Action When you discard this from play, you may put this on top of your deck if you have a Potion in play.,,,,,,")); Alchemist.FixName();
    Altar.Set(QString("Altar"),QString("Dark Ages"),QString("$6"),QString("Action"),QString("Trash a card from your hand. Gain a card costing up to 5 Coins.,,,,,,")); Altar.FixName();
    Ambassador.Set(QString("Ambassador"),QString("Seaside"),QString("$3"),QString("Action - Attack"),QString("Reveal a card from your hand. Return up to 2 copies of it from your hand to the Supply. Then each other player gains a copy of it.,,,,,,")); Ambassador.FixName();
    Apothecary.Set(QString("Apothecary"),QString("Alchemy"),QString("$2 1P"),QString("Action"),QString("+1 Card +1 Action  Reveal the top 4 cards of your deck. Put the revealed Coppers and Potions into your hand. Put the other cards back on top of your deck in any order.,,,,,,")); Apothecary.FixName();
    Apprentice.Set(QString("Apprentice"),QString("Alchemy"),QString("$5"),QString("Action"),QString("+1 Action Trash a card from your hand. +1 Card per Coin it costs. +2 Cards if it has Potion in its cost.,,,,,,")); Apprentice.FixName();
    Armory.Set(QString("Armory"),QString("Dark Ages"),QString("$4"),QString("Action"),QString("Gain a card costing up to 4 Coins")); Armory.FixName();
    BagofGold.Set(QString("BagofGold"),QString("Cornucopia"),QString("$0"),QString("Action - Prize"),QString("+1 Action Gain a Gold, putting it on top of your deck. (This is not in the Supply.),,,,,,")); BagofGold.FixName();
    Baker.Set(QString("Baker"),QString("Guilds"),QString("$5"),QString("Action"),QString("+1 Card. +1 Action. Take a Coin token. — Setup: Each player takes a Coin token.,,,,,,")); Baker.FixName();
    BanditCamp.Set(QString("BanditCamp"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("+1 Card, +2 Actions Gain a Spoils from the Spoils pile.,,,,,,")); BanditCamp.FixName();
    BandofMisfits.Set(QString("BandofMisfits"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("Play this as if it were an Action card in the Supply costing less than it that you choose. This is that card until it leaves play.,,,,,,")); BandofMisfits.FixName();
    Bank.Set(QString("Bank"),QString("Prosperity"),QString("$7"),QString("Treasure"),QString("Worth ? Coins. When you play this, it`s worth 1 Coin per Treasure card you have in play (counting this).,,,,,,")); Bank.FixName();
    Baron.Set(QString("Baron"),QString("Intrigue"),QString("$4"),QString("Action"),QString("+1 Buy")); Baron.FixName();
    Bazaar.Set(QString("Bazaar"),QString("Seaside"),QString("$5"),QString("Action"),QString("+1 Card")); Bazaar.FixName();
    Beggar.Set(QString("Beggar"),QString("Dark Ages"),QString("$2"),QString("Action - Reaction"),QString("Gain 3 Coppers, putting them into your hand.   When another player plays an Attack card, you may discard this. If you do, gain two Silvers, putting one on top of your deck.,,,,,,")); Beggar.FixName();
    Bishop.Set(QString("Bishop"),QString("Prosperity"),QString("$4"),QString("Action"),QString("+1 Coin +1 <VP> Trash a card from your hand. +<VP> equal to half its cost in Coins, rounded down. Each other player may trash a card from his hand.,,,,,,")); Bishop.FixName();
    BlackMarket.Set(QString("BlackMarket"),QString("Promo"),QString("$3"),QString("Action"),QString("+2 Coins, Reveal the top 3 cards of the Black Market deck. You may buy one of them immediately. Put the unbought cards on the bottom of the Black Market deck in any order.  (Before the game, make a Black Market deck out of one copy of each Kingdom card not in the supply.).,,,,,,")); BlackMarket.FixName();
    BorderVillage.Set(QString("BorderVillage"),QString("Hinterlands"),QString("$6"),QString("Action"),QString("+1 Card +2 Actions   When you gain this, gain a card costing less than this.,,,,,,")); BorderVillage.FixName();
    Bridge.Set(QString("Bridge"),QString("Intrigue"),QString("$4"),QString("Action"),QString("+1 Buy")); Bridge.FixName();
    Bureaucrat.Set(QString("Bureaucrat"),QString("Base"),QString("$4"),QString("Action - Attack"),QString("Gain a silver card")); Bureaucrat.FixName();
    Butcher.Set(QString("Butcher"),QString("Guilds"),QString("$5"),QString("Action"),QString("Take 2 Coin tokens. You may trash a card from your hand and then pay any number of Coin tokens. If you did trash a card")); Butcher.FixName();
    Cache.Set(QString("Cache"),QString("Hinterlands"),QString("$5"),QString("Treasure"),QString("Worth 3 Coins   When you gain this, gain two Coppers.,,,,,,")); Cache.FixName();
    CandlestickMaker.Set(QString("CandlestickMaker"),QString("Guilds"),QString("$2"),QString("Action"),QString("+1 Action. +1 Buy. Take a Coin token.,,,,,,")); CandlestickMaker.FixName();
    Caravan.Set(QString("Caravan"),QString("Seaside"),QString("$4"),QString("Action - Duration"),QString("+1 Card, +1 Action At the start of your next turn, +1 Card.,,,,,,")); Caravan.FixName();
    Cartographer.Set(QString("Cartographer"),QString("Hinterlands"),QString("$5"),QString("Action"),QString("+1 Card +1 Action Look at the top 4 cards of your deck. Discard any number of them. Put the rest back on top in any order.,,,,,,")); Cartographer.FixName();
    Catacombs.Set(QString("Catacombs"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("Look at the top 3 cards of your deck. Choose one: Put them into your hand; or discard them and +3 Cards.   When you trash this, gain a cheaper card.,,,,,,")); Catacombs.FixName();
    Cellar.Set(QString("Cellar"),QString("Base"),QString("$2"),QString("Action"),QString("+1 Action")); Cellar.FixName();
    Chancellor.Set(QString("Chancellor"),QString("Base"),QString("$3"),QString("Action"),QString("+2 Coins")); Chancellor.FixName();
    Chapel.Set(QString("Chapel"),QString("Base"),QString("$2"),QString("Action"),QString("Trash up to 4 cards from your hand.,,,,,,")); Chapel.FixName();
    City.Set(QString("City"),QString("Prosperity"),QString("$5"),QString("Action"),QString("+1 Card +2 Actions If there are one or more empty Supply piles, +1 Card. If there are two or more, +1 Coin and +1 Buy.,,,,,,")); City.FixName();
    Colony.Set(QString("Colony"),QString("Prosperity"),QString("$11"),QString("Victory"),QString("10 <VP>.,,,,,,")); Colony.FixName();
    Conspirator.Set(QString("Conspirator"),QString("Intrigue"),QString("$4"),QString("Action"),QString("+2 Coins. If you've played 3 or more Actions this turn (counting this): +1 Card")); Conspirator.FixName();
    Contraband.Set(QString("Contraband"),QString("Prosperity"),QString("$5"),QString("Treasure"),QString("Worth 3 Coins. +1 Buy When you play this, the player to your left names a card. You can't buy that card this turn.,,,,,,")); Contraband.FixName();
    Coppersmith.Set(QString("Coppersmith"),QString("Intrigue"),QString("$4"),QString("Action"),QString("Copper produces an extra 1 Coin this turn.,,,,,,")); Coppersmith.FixName();
    CouncilRoom.Set(QString("CouncilRoom"),QString("Base"),QString("$5"),QString("Action"),QString("+4 Cards")); CouncilRoom.FixName();
    Count.Set(QString("Count"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("Choose one: Discard 2 cards; or put a card from your hand on top of your deck; or gain a Copper. Choose one: +3 Coins; or trash your hand; or gain a Duchy.,,,,,,")); Count.FixName();
    Counterfeit.Set(QString("Counterfeit"),QString("Dark Ages"),QString("$5"),QString("Treasure"),QString("1 Coin +1 Buy When you play this, you may play a Treasure from your hand twice. If you do, trash that Treasure.,,,,,,")); Counterfeit.FixName();
    CountingHouse.Set(QString("CountingHouse"),QString("Prosperity"),QString("$5"),QString("Action"),QString("Look through your discard pile")); CountingHouse.FixName();
    Courtyard.Set(QString("Courtyard"),QString("Intrigue"),QString("$2"),QString("Action"),QString("+3 Card")); Courtyard.FixName();
    Crossroads.Set(QString("Crossroads"),QString("Hinterlands"),QString("$2"),QString("Action"),QString("Reveal your hand. +1 Card per Victory card revealed. If this is the first time you played a Crossroads this turn, +3 Actions.,,,,,,")); Crossroads.FixName();
    Cultist.Set(QString("Cultist"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Looter"),QString("+2 Cards Each other player gains a Ruins. You may play a Cultist from your hand.   When you trash this, +3 Cards.,,,,,,")); Cultist.FixName();
    Cutpurse.Set(QString("Cutpurse"),QString("Seaside"),QString("$4"),QString("Action - Attack"),QString("+2 Coins")); Cutpurse.FixName();
    DameAnna.Set(QString("DameAnna"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("You may trash up to 2 cards from your hand. Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); DameAnna.FixName();
    DameJosephine.Set(QString("DameJosephine"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight - Victory"),QString("2 Victory Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); DameJosephine.FixName();
    DameMolly.Set(QString("DameMolly"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("+2 Actions Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); DameMolly.FixName();
    DameNatalie.Set(QString("DameNatalie"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("You may gain a card costing up to 3 Coins. Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); DameNatalie.FixName();
    DameSylvia.Set(QString("DameSylvia"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("+2 Coins Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); DameSylvia.FixName();
    DeathCart.Set(QString("DeathCart"),QString("Dark Ages"),QString("$4"),QString("Action - Looter"),QString("+5 Coins You may trash an Action card from your hand. If you don't, trash this.   When you gain this, gain 2 Ruins.,,,,,,")); DeathCart.FixName();
    Develop.Set(QString("Develop"),QString("Hinterlands"),QString("$3"),QString("Action"),QString("Trash a card from your hand. Gain a card costing exactly 1 Coin more than it and a card costing exactly 1 less than it")); Develop.FixName();
    Diadem.Set(QString("Diadem"),QString("Cornucopia"),QString("$0"),QString("Treasure - Prize"),QString("Worth 2 Coins. When you play this, +1 Coin per unused Action you have (Action, not Action card). (This is not in the Supply.),,,,,,")); Diadem.FixName();
    Doctor.Set(QString("Doctor"),QString("Guilds"),QString("$3+"),QString("Action"),QString("Name a card. Reveal the top 3 cards of your deck. Trash the matches. Put the rest back on top in any order. — When you buy this, you may overpay for it. For each $1 you overpaid, look at the top card of your deck; trash it, discard it, or put it back.,,,,,,")); Doctor.FixName();
    Duchess.Set(QString("Duchess"),QString("Hinterlands"),QString("$2"),QString("Action"),QString("+2 Coins Each player (including you) looks at the top card of his deck, and discards it or puts it back.   In games using this, when you gain a Duchy, you may gain a Duchess.,,,,,,")); Duchess.FixName();
    Duke.Set(QString("Duke"),QString("Intrigue"),QString("$5"),QString("Victory"),QString("Worth 1 Victory per Duchy you have.,,,,,,")); Duke.FixName();
    Embargo.Set(QString("Embargo"),QString("Seaside"),QString("$2"),QString("Action"),QString("+2 Coins")); Embargo.FixName();
    Embassy.Set(QString("Embassy"),QString("Hinterlands"),QString("$5"),QString("Action"),QString("+5 Cards Discard 3 cards.   When you gain this, each other player gains a Silver.,,,,,,")); Embassy.FixName();
    Envoy.Set(QString("Envoy"),QString("Promo"),QString("$4"),QString("Action"),QString("Reveal the top 5 cards of your deck. The player to your left chooses one for you to discard. Draw the rest.,,,,,,")); Envoy.FixName();
    Expand.Set(QString("Expand"),QString("Prosperity"),QString("$7"),QString("Action"),QString("Trash a card from your hand. Gain a card costing up to 3 Coins more than the trashed card.,,,,,,")); Expand.FixName();
    Explorer.Set(QString("Explorer"),QString("Seaside"),QString("$5"),QString("Action"),QString("You may reveal a Province card from your hand. If you do")); Explorer.FixName();
    Fairgrounds.Set(QString("Fairgrounds"),QString("Cornucopia"),QString("$6"),QString("Victory"),QString("Worth 2 VP for every 5 differently named cards in your deck (rounded down),,,,,,")); Fairgrounds.FixName();
    Familiar.Set(QString("Familiar"),QString("Alchemy"),QString("$3 1P"),QString("Action - Attack"),QString("+1 Card +1 Action Each other player gains a curse.,,,,,,")); Familiar.FixName();
    FarmingVillage.Set(QString("FarmingVillage"),QString("Cornucopia"),QString("$4"),QString("Action"),QString("+2 Actions Reveal cards from the top of your deck until you reveal an Action or Treasure card. Put that card into your hand and discard the other cards.,,,,,,")); FarmingVillage.FixName();
    Farmland.Set(QString("Farmland"),QString("Hinterlands"),QString("$6"),QString("Victory"),QString("2 VP   When you buy this, trash a card from your hand. Gain a card costing exactly 2 Coins more than the trashed card.,,,,,,")); Farmland.FixName();
    Feast.Set(QString("Feast"),QString("Base"),QString("$4"),QString("Action"),QString("Trash this card. Gain a card costing up to 5 Coins.,,,,,,")); Feast.FixName();
    Feodum.Set(QString("Feodum"),QString("Dark Ages"),QString("$4"),QString("Victory"),QString("Worth 1 Victory for every 3 Silvers in your deck (round down).   When you trash this, gain 3 Silvers.,,,,,,")); Feodum.FixName();
    Festival.Set(QString("Festival"),QString("Base"),QString("$5"),QString("Action"),QString("+2 Actions")); Festival.FixName();
    FishingVillage.Set(QString("FishingVillage"),QString("Seaside"),QString("$3"),QString("Action - Duration"),QString("+2 Actions")); FishingVillage.FixName();
    Followers.Set(QString("Followers"),QString("Cornucopia"),QString("$0"),QString("Action - Attack - Prize"),QString("+2 Cards Gain an Estate. Each other player gains a Curse and discards down to 3 cards in hand. (This is not in the Supply.),,,,,,")); Followers.FixName();
    FoolsGold.Set(QString("FoolsGold"),QString("Hinterlands"),QString("$2"),QString("Treasure - Reaction"),QString("If this is the first time you played a Fool's Gold this turn, this is worth 1 Coin, otherwise it's worth 4 Coins.   When another player gains a Province, you may trash this from your hand. If you do, gain a Gold, putting it on your deck.,,,,,,")); FoolsGold.FixName();
    Forager.Set(QString("Forager"),QString("Dark Ages"),QString("$3"),QString("Action"),QString("+1 Action, +1 Buy Trash a card from your hand. +1 Coin per differently named Treasure in the trash.,,,,,,")); Forager.FixName();
    Forge.Set(QString("Forge"),QString("Prosperity"),QString("$7"),QString("Action"),QString("Trash any number of cards from your hand. Gain a card with cost exactly equal to the total cost in Coins of the trashed cards.,,,,,,")); Forge.FixName();
    Fortress.Set(QString("Fortress"),QString("Dark Ages"),QString("$4"),QString("Action"),QString("+1 Card, +2 Actions   When you trash this, put it into your hand.,,,,,,")); Fortress.FixName();
    FortuneTeller.Set(QString("FortuneTeller"),QString("Cornucopia"),QString("$3"),QString("Action - Attack"),QString("+2 Coins Each other player reveals cards from the top of his deck until he reveals a Victory or Curse card. He puts it on top and discards the other revealed cards.,,,,,,")); FortuneTeller.FixName();
    Gardens.Set(QString("Gardens"),QString("Base"),QString("$4"),QString("Victory"),QString("Variable")); Gardens.FixName();
    GhostShip.Set(QString("GhostShip"),QString("Seaside"),QString("$5"),QString("Action - Attack"),QString("+2 Card")); GhostShip.FixName();
    Golem.Set(QString("Golem"),QString("Alchemy"),QString("$4 1P"),QString("Action"),QString("Reveal cards from your deck until you reveal 2 Action cards other than Golem Cards. Discard the other cards, then play the Action cards in either order.,,,,,,")); Golem.FixName();
    Goons.Set(QString("Goons"),QString("Prosperity"),QString("$6"),QString("Action - Attack"),QString("+1 Buy +2 Coins Each other player discards down to 3 cards in hand.   While this is in play, when you buy a card, +1 <VP>.,,,,,,")); Goons.FixName();
    Governor.Set(QString("Governor"),QString("Promo"),QString("$5"),QString("Action"),QString("+1 Action  Choose one; you get the version in parentheses: Each player gets +1 (+3) Cards; or each player gains a Silver (Gold); or each player may trash a card from his hand and gain a card costing exactly 1 Coin (2 Coins) more.,,,,,,")); Governor.FixName();
    GrandMarket.Set(QString("GrandMarket"),QString("Prosperity"),QString("$6"),QString("Action"),QString("+1 Card +1 Action +1 Buy +2 Coins   You can't buy this if you have any Copper in play.,,,,,,")); GrandMarket.FixName();
    Graverobber.Set(QString("Graverobber"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("Choose one: Gain a card from the trash costing from 3 Coins to 6 Coins")); Graverobber.FixName();
    GreatHall.Set(QString("GreatHall"),QString("Intrigue"),QString("$3"),QString("Action - Victory"),QString("1 Victory")); GreatHall.FixName();
    Haggler.Set(QString("Haggler"),QString("Hinterlands"),QString("$5"),QString("Action"),QString("+2 Coins   While this is in play, when you buy a card, gain a card costing less than it that is not a Victory card.,,,,,,")); Haggler.FixName();
    Hamlet.Set(QString("Hamlet"),QString("Cornucopia"),QString("$2"),QString("Action"),QString("+1 Card +1 Action  You may discard a card; If you do, +1 Action. You may discard a card; If you do, +1 Buy.,,,,,,")); Hamlet.FixName();
    Harem.Set(QString("Harem"),QString("Intrigue"),QString("$6"),QString("Treasure - Victory"),QString("2 Coins")); Harem.FixName();
    Harvest.Set(QString("Harvest"),QString("Cornucopia"),QString("$5"),QString("Action"),QString("Reveal the top 4 cards of your deck")); Harvest.FixName();
    Haven.Set(QString("Haven"),QString("Seaside"),QString("$2"),QString("Action - Duration"),QString("+1 Card")); Haven.FixName();
    Herald.Set(QString("Herald"),QString("Guilds"),QString("$4+"),QString("Action"),QString("+1 Card. +1 Action. Reveal the top card of your deck. If it is an Action, play it. — When you buy this, you may overpay for it. For each $1 you overpaid, look through your discard pile and put a card from it on top of your deck.,,,,,,")); Herald.FixName();
    Herbalist.Set(QString("Herbalist"),QString("Alchemy"),QString("$2"),QString("Action"),QString("+1 Buy +1 Coin When you discard this from play, you may put one of your Treasures from play on top of your deck.,,,,,,")); Herbalist.FixName();
    Hermit.Set(QString("Hermit"),QString("Dark Ages"),QString("$3"),QString("Action"),QString("Look through your discard pile. You may trash a card from your discard pile or hand that is not a Treasure. Gain a card costing up to 3 Coins.   When you discard this from play, if you did not buy any cards this turn, trash this and gain a Madman from the Madman pile.,,,,,,")); Hermit.FixName();
    Highway.Set(QString("Highway"),QString("Hinterlands"),QString("$5"),QString("Action"),QString("+1 Card +1 Action   While this is in play, cards cost 1 Coin less, but not less than 0 Coins.,,,,,,")); Highway.FixName();
    Hoard.Set(QString("Hoard"),QString("Prosperity"),QString("$6"),QString("Treasure"),QString("Worth 2 Coins.   While this is in play, when you buy a Victory card, gain a Gold.,,,,,,")); Hoard.FixName();
    HornofPlenty.Set(QString("HornofPlenty"),QString("Cornucopia"),QString("$5"),QString("Treasure"),QString("0 Coins When you play this, gain a card costing up to 1 Coin per differently named card you have in play, counting this. If it’s a Victory card, trash this.,,,,,,")); HornofPlenty.FixName();
    HorseTraders.Set(QString("HorseTraders"),QString("Cornucopia"),QString("$4"),QString("Action - Reaction"),QString("+1 Buy +3 Coins Discard 2 Cards   When another player plays an Attack card, you may set this aside from your hand. If you do, then at the start of your next turn, +1 Card and return this to your hand.,,,,,,")); HorseTraders.FixName();
    Hovel.Set(QString("Hovel"),QString("Dark Ages"),QString("$1"),QString("Reaction - Shelter"),QString("When you buy a Victory card")); Hovel.FixName();
    HuntingGrounds.Set(QString("HuntingGrounds"),QString("Dark Ages"),QString("$6"),QString("Action"),QString("+4 Cards   When you trash this, gain a Duchy or 3 Estates.,,,,,,")); HuntingGrounds.FixName();
    HuntingParty.Set(QString("HuntingParty"),QString("Cornucopia"),QString("$5"),QString("Action"),QString("+1 Card +1 Action Reveal your hand. Reveal cards from your deck until you reveal a card that isn’t a duplicate of one in your hand. Put it into your hand and discard the rest.,,,,,,")); HuntingParty.FixName();
    IllGottenGains.Set(QString("IllGottenGains"),QString("Hinterlands"),QString("$5"),QString("Treasure"),QString("Worth 1 Coin When you play this, you may gain a Copper, putting it into your hand.   When you gain this, each other player gains a Curse.,,,,,,")); IllGottenGains.FixName();
    Inn.Set(QString("Inn"),QString("Hinterlands"),QString("$5"),QString("Action"),QString("+2 Cards +2 Actions Discard 2 cards.   When you gain this, look through your discard pile (including this), reveal any number of Action cards from it, and shuffle them into your deck.,,,,,,")); Inn.FixName();
    Ironmonger.Set(QString("Ironmonger"),QString("Dark Ages"),QString("$4"),QString("Action"),QString("+1 Card, +1 Action Reveal the top card of your deck; you may discard it. Either way, if it is an… Action card, +1 Action Treasure card, +1 Coin Victory card, +1 Card,,,,,,")); Ironmonger.FixName();
    Ironworks.Set(QString("Ironworks"),QString("Intrigue"),QString("$4"),QString("Action"),QString("Gain a card costing up to 4 Coins. If it is an... Action card")); Ironworks.FixName();
    Island.Set(QString("Island"),QString("Seaside"),QString("$4"),QString("Action - Victory"),QString("Set aside this and another card from your hand. Return them to your deck at the end of the game.   2 VP,,,,,,")); Island.FixName();
    JackofallTrades.Set(QString("JackofallTrades"),QString("Hinterlands"),QString("$4"),QString("Action"),QString("Gain a Silver. Look at the top card of your deck; discard it or put it back. Draw until you have 5 cards in hand. You may trash a card from your hand that is not a Treasure.,,,,,,")); JackofallTrades.FixName();
    Jester.Set(QString("Jester"),QString("Cornucopia"),QString("$5"),QString("Action - Attack"),QString("+2 Coins Each other player discards the top card of his deck. If it’s a Victory card he gains a Curse. Otherwise he gains a copy of the discarded card or you do, your choice.,,,,,,")); Jester.FixName();
    Journeyman.Set(QString("Journeyman"),QString("Guilds"),QString("$5"),QString("Action"),QString("Name a card. Reveal cards from the top of your deck until you reveal 3 cards that are not the named card. Put those cards into your hand and discard the rest.,,,,,,")); Journeyman.FixName();
    JunkDealer.Set(QString("JunkDealer"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("+1 Card, +1 Action, +1 Coin Trash a card from your hand.,,,,,,")); JunkDealer.FixName();
    KingsCourt.Set(QString("KingsCourt"),QString("Prosperity"),QString("$7"),QString("Action"),QString("You may choose an Action card in your hand. Play it three times.,,,,,,")); KingsCourt.FixName();
    Laboratory.Set(QString("Laboratory"),QString("Base"),QString("$5"),QString("Action"),QString("+2 Cards")); Laboratory.FixName();
    Library.Set(QString("Library"),QString("Base"),QString("$5"),QString("Action"),QString("Draw until you have 7 cards in hand. You may set aside any Action cards drawn this way")); Library.FixName();
    Lighthouse.Set(QString("Lighthouse"),QString("Seaside"),QString("$2"),QString("Action - Duration"),QString("+1 Action")); Lighthouse.FixName();
    Loan.Set(QString("Loan"),QString("Prosperity"),QString("$3"),QString("Treasure"),QString("Worth 1 Coin. When you play this, reveal cards from your deck until you reveal a Treasure. Discard it or trash it. Discard the other cards.,,,,,,")); Loan.FixName();
    Lookout.Set(QString("Lookout"),QString("Seaside"),QString("$3"),QString("Action"),QString("+1 Action")); Lookout.FixName();
    Madman.Set(QString("Madman"),QString("Dark Ages"),QString("$0"),QString("Action"),QString("+2 Actions Return this to the Madman pile. If you do, +1 Card per card in your hand. (This card is not in the supply.),,,,,,")); Madman.FixName();
    Mandarin.Set(QString("Mandarin"),QString("Hinterlands"),QString("$5"),QString("Action"),QString("+3 Coins Put a card from your hand on top of your deck.   When you gain this, put all Treasures you have in play on top of your deck in any order.,,,,,,")); Mandarin.FixName();
    Marauder.Set(QString("Marauder"),QString("Dark Ages"),QString("$4"),QString("Action - Attack - Looter"),QString("Gain a Spoils from the Spoils pile. Each other player gains a Ruins.,,,,,,")); Marauder.FixName();
    Margrave.Set(QString("Margrave"),QString("Hinterlands"),QString("$5"),QString("Action - Attack"),QString("+3 Cards +1 Buy Each other player draws a card, then discards down to 3 cards in hand.,,,,,,")); Margrave.FixName();
    Market.Set(QString("Market"),QString("Base"),QString("$5"),QString("Action"),QString("+1 Card")); Market.FixName();
    MarketSquare.Set(QString("MarketSquare"),QString("Dark Ages"),QString("$3"),QString("Action - Reaction"),QString("+1 Card, +1 Action, +1 Buy   When one of your cards is trashed, you may discard this from your hand. If you do, gain a Gold.,,,,,,")); MarketSquare.FixName();
    Masquerade.Set(QString("Masquerade"),QString("Intrigue"),QString("$3"),QString("Action"),QString("+2 Cards  Each player passes a card from his hand to the left at once. Then you may trash a card from your hand.,,,,,,")); Masquerade.FixName();
    Masterpiece.Set(QString("Masterpiece"),QString("Guilds"),QString("$3+"),QString("Treasure"),QString("Worth $1 — When you buy this, you may overpay for it. If you do, gain a Silver per $1 you overpaid.,,,,,,")); Masterpiece.FixName();
    Menagerie.Set(QString("Menagerie"),QString("Cornucopia"),QString("$3"),QString("Action"),QString("+1 Action Reveal your hand. If there are no duplicate cards in it, +3 Cards. Otherwise, +1 Card.,,,,,,")); Menagerie.FixName();
    Mercenary.Set(QString("Mercenary"),QString("Dark Ages"),QString("$0"),QString("Action - Attack"),QString("You may trash 2 cards from your hand. If you do")); Mercenary.FixName();
    MerchantGuild.Set(QString("MerchantGuild"),QString("Guilds"),QString("$5"),QString("Action"),QString("+1 Buy. +$1. — While this is in play, when you buy a card, take a Coin token.,,,,,,")); MerchantGuild.FixName();
    MerchantShip.Set(QString("MerchantShip"),QString("Seaside"),QString("$5"),QString("Action - Duration"),QString("Now and at the start of your next turn: +2 Coins.,,,,,,")); MerchantShip.FixName();
    Militia.Set(QString("Militia"),QString("Base"),QString("$4"),QString("Action - Attack"),QString("+2 Coins")); Militia.FixName();
    Mine.Set(QString("Mine"),QString("Base"),QString("$5"),QString("Action"),QString("Trash a Treasure card from your hand. Gain a Treasure card costing up to 3 Coins more")); Mine.FixName();
    MiningVillage.Set(QString("MiningVillage"),QString("Intrigue"),QString("$4"),QString("Action"),QString("+1 Card")); MiningVillage.FixName();
    Minion.Set(QString("Minion"),QString("Intrigue"),QString("$5"),QString("Action - Attack"),QString("+1 Action")); Minion.FixName();
    Mint.Set(QString("Mint"),QString("Prosperity"),QString("$5"),QString("Action"),QString("You may reveal a Treasure card from your hand. Gain a copy of it.   When you buy this, trash all Treasures you have in play.,,,,,,")); Mint.FixName();
    Moat.Set(QString("Moat"),QString("Base"),QString("$2"),QString("Action - Reaction"),QString("+2 Cards")); Moat.FixName();
    Moneylender.Set(QString("Moneylender"),QString("Base"),QString("$4"),QString("Action"),QString("Trash a Copper from your hand. If you do")); Moneylender.FixName();
    Monument.Set(QString("Monument"),QString("Prosperity"),QString("$4"),QString("Action"),QString("+2 Coins")); Monument.FixName();
    Mountebank.Set(QString("Mountebank"),QString("Prosperity"),QString("$5"),QString("Action - Attack"),QString("+2 Coins Each other player may discard a Curse. If he doesn't, he gains a Curse and a Copper.,,,,,,")); Mountebank.FixName();
    Mystic.Set(QString("Mystic"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("+1 Action, +2 Coins Name a card. Reveal the top card of your deck. If it's the named card, put it into your hand.,,,,,,")); Mystic.FixName();
    NativeVillage.Set(QString("NativeVillage"),QString("Seaside"),QString("$2"),QString("Action"),QString("+2 Actions, Choose one: Set aside the top card of your deck face down on your Native Village mat; or put all the cards from your mat into your hand.   You may look at the cards on your mat at any time; return them to your deck at the end of the game.,,,,,,")); NativeVillage.FixName();
    Navigator.Set(QString("Navigator"),QString("Seaside"),QString("$4"),QString("Action"),QString("+2 Coins")); Navigator.FixName();
    Necropolis.Set(QString("Necropolis"),QString("Dark Ages"),QString("$1"),QString("Action - Shelter"),QString("+2 Actions,,,,,,")); Necropolis.FixName();
    NobleBrigand.Set(QString("NobleBrigand"),QString("Hinterlands"),QString("$4"),QString("Action - Attack"),QString("+1 Coin When you buy this or play it, each other player reveals the top 2 cards of his deck, trashes a revealed Silver or Gold you choose, and discards the rest. If he didn't reveal a Treasure, he gains a Copper. You gain the trashed cards.,,,,,,")); NobleBrigand.FixName();
    Nobles.Set(QString("Nobles"),QString("Intrigue"),QString("$6"),QString("Action - Victory"),QString("2 Victory")); Nobles.FixName();
    NomadCamp.Set(QString("NomadCamp"),QString("Hinterlands"),QString("$4"),QString("Action"),QString("+1 Buy +2 Coins   When you gain this, put it on top of your deck.,,,,,,")); NomadCamp.FixName();
    Oasis.Set(QString("Oasis"),QString("Hinterlands"),QString("$3"),QString("Action"),QString("+1 Card +1 Action +1 Coin Discard a card.,,,,,,")); Oasis.FixName();
    Oracle.Set(QString("Oracle"),QString("Hinterlands"),QString("$3"),QString("Action - Attack"),QString("Each player (including you) reveals the top 2 cards of his deck, and you choose one: either he discards them, or he puts them back on top in an order he chooses. +2 Cards,,,,,,")); Oracle.FixName();
    Outpost.Set(QString("Outpost"),QString("Seaside"),QString("$5"),QString("Action - Duration"),QString("You only draw 3 cards (instead of 5) in this turn's Clean-up phase. Take an extra turn after this one. This can't cause you to take more than two consecutive turns.,,,,,,")); Outpost.FixName();
    OvergrownEstate.Set(QString("OvergrownEstate"),QString("Dark Ages"),QString("$1"),QString("Victory - Shelter"),QString("0 Victory   When you trash this, +1 Card.,,,,,,")); OvergrownEstate.FixName();
    Pawn.Set(QString("Pawn"),QString("Intrigue"),QString("$2"),QString("Action"),QString("Choose two: +1 Card")); Pawn.FixName();
    PearlDiver.Set(QString("PearlDiver"),QString("Seaside"),QString("$2"),QString("Action"),QString("+1 Card")); PearlDiver.FixName();
    Peddler.Set(QString("Peddler"),QString("Prosperity"),QString("$8"),QString("Action"),QString("+1 Card; +1 Action; +1 Coin   During your Buy phase, this costs 2 Coins less per Action card you have in play, but not less than 0 Coins.,,,,,,")); Peddler.FixName();
    PhilosophersStone.Set(QString("PhilosophersStone"),QString("Alchemy"),QString("$3 1P"),QString("Treasure"),QString("When you play this, count your deck and discard pile. Worth 1 Coin per 5 cards total between them (rounded down).,,,,,,")); PhilosophersStone.FixName();
    Pillage.Set(QString("Pillage"),QString("Dark Ages"),QString("$5"),QString("Action - Attack"),QString("Trash this. Each other player with 5 or more cards in hand reveals his hand and discards a card that you choose. Gain 2 Spoils from the Spoils pile.,,,,,,")); Pillage.FixName();
    PirateShip.Set(QString("PirateShip"),QString("Seaside"),QString("$4"),QString("Action - Attack"),QString("Choose one: Each other player reveals the top 2 cards of his deck")); PirateShip.FixName();
    Platinum.Set(QString("Platinum"),QString("Prosperity"),QString("$9"),QString("Treasure"),QString("5 Coins.,,,,,,")); Platinum.FixName();
    Plaza.Set(QString("Plaza"),QString("Guilds"),QString("$4"),QString("Action"),QString("+1 Card. +2 Actions. You may discard a Treasure card. If you do")); Plaza.FixName();
    PoorHouse.Set(QString("PoorHouse"),QString("Dark Ages"),QString("$1"),QString("Action"),QString("+4 Coins Reveal your hand. -1 Coin per Treasure card in your hand, to a minimum of 0 Coins.,,,,,,")); PoorHouse.FixName();
    Possession.Set(QString("Possession"),QString("Alchemy"),QString("$6 1P"),QString("Action"),QString("The player to your left takes an extra turn after this one, in which you can see all cards he can and make all decisions for him. Any cards he would gain on that turn, you gain instead; any cards of his that are trashed are set aside and returned to his discard pile at end of turn.,,,,,,")); Possession.FixName();
    Potion.Set(QString("Potion"),QString("Alchemy"),QString("$4"),QString("Treasure"),QString("Worth 1 Potion.,,,,,,")); Potion.FixName();
    Princess.Set(QString("Princess"),QString("Cornucopia"),QString("$0"),QString("Action - Prize"),QString("+1 Buy   While this is in play, cards cost 2 Coins less, but not less than 0 Coins. (This is not in the Supply.),,,,,,")); Princess.FixName();
    Procession.Set(QString("Procession"),QString("Dark Ages"),QString("$4"),QString("Action"),QString("You may play an Action card from your hand twice. Trash it. Gain an Action card costing exactly 1 Coin more than it.,,,,,,")); Procession.FixName();
    Quarry.Set(QString("Quarry"),QString("Prosperity"),QString("$4"),QString("Treasure"),QString("Worth 1 Coin.   While this is in play, Action cards cost 2 Coins less, but not less than 0 Coins.,,,,,,")); Quarry.FixName();
    Rabble.Set(QString("Rabble"),QString("Prosperity"),QString("$5"),QString("Action - Attack"),QString("+3 Cards Each other player reveals the top 3 cards of his deck, discards the revealed Actions and Treasures, and puts the rest back on top in any order he chooses.,,,,,,")); Rabble.FixName();
    Rats.Set(QString("Rats"),QString("Dark Ages"),QString("$4"),QString("Action"),QString("+1 Card, +1 Action Gain a Rats. Trash a card from your hand other than a Rats (or reveal a hand of all Rats).   When you tash this, +1 Card.,,,,,,")); Rats.FixName();
    Rebuild.Set(QString("Rebuild"),QString("Dark Ages"),QString("$5"),QString("Action"),QString("+1 Action  Name a card. Reveal cards from the top of your deck until you reveal a Victory card that is not the named card. Discard the other cards. Trash the Victory card and gain a Victory card costing up to 3 Coins more than it.,,,,,,")); Rebuild.FixName();
    Remake.Set(QString("Remake"),QString("Cornucopia"),QString("$4"),QString("Action"),QString("Do this twice: Trash a card from your hand")); Remake.FixName();
    Remodel.Set(QString("Remodel"),QString("Base"),QString("$4"),QString("Action"),QString("Trash a card from your hand. Gain a card costing up to 2 Coins more than the trashed card.,,,,,,")); Remodel.FixName();
    Rogue.Set(QString("Rogue"),QString("Dark Ages"),QString("$5"),QString("Action - Attack"),QString("+2 Coins If there are any cards in the trash costing from 3 Coins to 6 Coins, gain one of them. Otherwise, each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest.,,,,,,")); Rogue.FixName();
    RoyalSeal.Set(QString("RoyalSeal"),QString("Prosperity"),QString("$5"),QString("Treasure"),QString("Worth 2 Coins.   While this is in play, when you gain a card, you may put that card on top of your deck.,,,,,,")); RoyalSeal.FixName();
    RuinedLibrary.Set(QString("RuinedLibrary"),QString("Dark Ages"),QString("$0"),QString("Action - Ruins"),QString("+1 Card,,,,,,")); RuinedLibrary.FixName();
    RuinedMarket.Set(QString("RuinedMarket"),QString("Dark Ages"),QString("$0"),QString("Action - Ruins"),QString("+1 Buy,,,,,,")); RuinedMarket.FixName();
    RuinedVillage.Set(QString("RuinedVillage"),QString("Dark Ages"),QString("$0"),QString("Action - Ruins"),QString("+1 Action,,,,,,")); RuinedVillage.FixName();
    Saboteur.Set(QString("Saboteur"),QString("Intrigue"),QString("$5"),QString("Action - Attack"),QString("Each other player reveals cards from the top of his deck until revealing one costing 3 Coins or more. He trashes that card and may gain a card costing at most 2 Coins less than it. He discards the other revealed cards.,,,,,,")); Saboteur.FixName();
    Sage.Set(QString("Sage"),QString("Dark Ages"),QString("$3"),QString("Action"),QString("+1 Action Reveal cards from the top of your deck until you reveal one costing 3 Coins or more. Put that card into your hand and discard the rest.,,,,,,")); Sage.FixName();
    Salvager.Set(QString("Salvager"),QString("Seaside"),QString("$4"),QString("Action"),QString("+1 Buy")); Salvager.FixName();
    Scavenger.Set(QString("Scavenger"),QString("Dark Ages"),QString("$4"),QString("Action"),QString("+1 Coins You may put your deck into your discard pile. Look through your discard pile and put one card from it on top of your deck.,,,,,,")); Scavenger.FixName();
    Scheme.Set(QString("Scheme"),QString("Hinterlands"),QString("$3"),QString("Action"),QString("+1 Card +1 Action At the start of Clean-up this turn, you may choose an Action card you have in play. If you discard it from play this turn, put it on your deck.,,,,,,")); Scheme.FixName();
    Scout.Set(QString("Scout"),QString("Intrigue"),QString("$4"),QString("Action"),QString("+1 Action. Reveal the top 4 cards of your deck. Put the revealed Victory cards into your hand. Put the other cards on top of your deck in any order.,,,,,,")); Scout.FixName();
    ScryingPool.Set(QString("ScryingPool"),QString("Alchemy"),QString("$2 1P"),QString("Action - Attack"),QString("+1 Action Each player (including you) reveals the top card of his deck and either discards it or puts it back, your choice. Then reveal cards from the top of your deck until revealing one that isn't an Action. Put all of your revealed cards into your hand.,,,,,,")); ScryingPool.FixName();
    SeaHag.Set(QString("SeaHag"),QString("Seaside"),QString("$4"),QString("Action - Attack"),QString("Each other player discards the top card of his deck")); SeaHag.FixName();
    SecretChamber.Set(QString("SecretChamber"),QString("Intrigue"),QString("$2"),QString("Action - Reaction"),QString("Discard any number of cards. +1 Coin per card discarded. - When another player plays an Attack card")); SecretChamber.FixName();
    ShantyTown.Set(QString("ShantyTown"),QString("Intrigue"),QString("$3"),QString("Action"),QString("+2 Actions")); ShantyTown.FixName();
    SilkRoad.Set(QString("SilkRoad"),QString("Hinterlands"),QString("$4"),QString("Victory"),QString("Worth 1 VP for every 4 Victory cards in your deck (round down).,,,,,,")); SilkRoad.FixName();
    SirBailey.Set(QString("SirBailey"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("+1 Card, +1 Action Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); SirBailey.FixName();
    SirDestry.Set(QString("SirDestry"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("+2 Cards Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); SirDestry.FixName();
    SirMartin.Set(QString("SirMartin"),QString("Dark Ages"),QString("$4"),QString("Action - Attack - Knight"),QString("+2 Buys Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); SirMartin.FixName();
    SirMichael.Set(QString("SirMichael"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("Each other player discards down to 3 cards in hand. Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.,,,,,,")); SirMichael.FixName();
    SirVander.Set(QString("SirVander"),QString("Dark Ages"),QString("$5"),QString("Action - Attack - Knight"),QString("Each other player reveals the top 2 cards of his deck, trashes one of them costing from 3 Coins to 6 Coins, and discards the rest. If a Knight is trashed by this, trash this card.   When you trash this, gain a Gold.,,,,,,")); SirVander.FixName();
    Smithy.Set(QString("Smithy"),QString("Base"),QString("$4"),QString("Action"),QString("+3 Cards.,,,,,,")); Smithy.FixName();
    Smugglers.Set(QString("Smugglers"),QString("Seaside"),QString("$3"),QString("Action"),QString("Gain a copy of a card costing up to 6 Coins that the player to your right gained on his last turn.,,,,,,")); Smugglers.FixName();
    Soothsayer.Set(QString("Soothsayer"),QString("Guilds"),QString("$5"),QString("Action – Attack"),QString("Gain a Gold. Each other player gains a Curse. Each player who did draws a card.,,,,,,")); Soothsayer.FixName();
    SpiceMerchant.Set(QString("SpiceMerchant"),QString("Hinterlands"),QString("$4"),QString("Action"),QString("You may trash a Treasure from your hand. If you do, choose one: +2 Cards and +1 Action; or +2 Coins and +1 Buy.,,,,,,")); SpiceMerchant.FixName();
    Spoils.Set(QString("Spoils"),QString("Dark Ages"),QString("$0"),QString("Treasure"),QString("3 Coins When you play this, return it to the Spoils pile. (This is not in the Supply.),,,,,,")); Spoils.FixName();
    Spy.Set(QString("Spy"),QString("Base"),QString("$4"),QString("Action - Attack"),QString("+1 Card +1 Action  Each player (including you) reveals the top card of his deck and either discards it or puts it back, your choice.,,,,,,")); Spy.FixName();
    Squire.Set(QString("Squire"),QString("Dark Ages"),QString("$2"),QString("Action"),QString("+1 Coin Choose one: +2 Actions; or +2 Buys; or gain a Silver.   When you trash this, gain an Attack card.,,,,,,")); Squire.FixName();
    Stables.Set(QString("Stables"),QString("Hinterlands"),QString("$5"),QString("Action"),QString("You may discard a Treasure. If you do")); Stables.FixName();
    Stash.Set(QString("Stash"),QString("Promo"),QString("$5"),QString("Treasure"),QString("Worth 2 Coins. When you shuffle")); Stash.FixName();
    Steward.Set(QString("Steward"),QString("Intrigue"),QString("$3"),QString("Action"),QString("Choose one: +2 Cards")); Steward.FixName();
    Stonemason.Set(QString("Stonemason"),QString("Guilds"),QString("$2+"),QString("Action"),QString("Trash a card from your hand. Gain 2 cards each costing less than it. — When you buy this, you may overpay for it. If you do, gain 2 Action cards each costing the amount you overpaid.,,,,,,")); Stonemason.FixName();
    Storeroom.Set(QString("Storeroom"),QString("Dark Ages"),QString("$3"),QString("Action"),QString("+1 Buy Discard any number of cards. +1 Card per card discarded. Discard any number of cards. +1 Coin per card discarded the second time.,,,,,,")); Storeroom.FixName();
    Survivors.Set(QString("Survivors"),QString("Dark Ages"),QString("$0"),QString("Action - Ruins"),QString("Look at the top 2 cards of your deck. Discard them or put them back in any order.,,,,,,")); Survivors.FixName();
    Swindler.Set(QString("Swindler"),QString("Intrigue"),QString("$3"),QString("Action - Attack"),QString("+2 Coins")); Swindler.FixName();
    Tactician.Set(QString("Tactician"),QString("Seaside"),QString("$5"),QString("Action - Duration"),QString("Discard your hand. If you discarded any cards this way")); Tactician.FixName();
    Talisman.Set(QString("Talisman"),QString("Prosperity"),QString("$4"),QString("Treasure"),QString("Worth 1 Coin.   While this is in play, when you buy a card costing 4 Coins or less that is not a Victory card, gain a copy of it.,,,,,,")); Talisman.FixName();
    Taxman.Set(QString("Taxman"),QString("Guilds"),QString("$4"),QString("Action – Attack"),QString("You may trash a Treasure from your hand. Each other player with 5 or more cards in hand discards a copy of it (or reveals a hand without it). Gain a Treasure card costing up to $3 more than the trashed card")); Taxman.FixName();
    Thief.Set(QString("Thief"),QString("Base"),QString("$4"),QString("Action - Attack"),QString("Each other player reveals the top 2 cards of his deck. If they revealed any Treasure cards")); Thief.FixName();
    ThroneRoom.Set(QString("ThroneRoom"),QString("Base"),QString("$4"),QString("Action"),QString("Choose an Action card in your hand. Play it twice.,,,,,,")); ThroneRoom.FixName();
    Torturer.Set(QString("Torturer"),QString("Intrigue"),QString("$5"),QString("Action - Attack"),QString("+3 Card")); Torturer.FixName();
    Tournament.Set(QString("Tournament"),QString("Cornucopia"),QString("$4"),QString("Action"),QString("+1 Action Each player may reveal a Province from his hand. If you do, discard it and gain a Prize (from the Prize pile) or a Duchy, putting it on top of your deck. If no-one else does, +1 Card +1 Coin.,,,,,,")); Tournament.FixName();
    TradeRoute.Set(QString("TradeRoute"),QString("Prosperity"),QString("$3"),QString("Action"),QString("+1 Buy +1 Coin per token on the Trade Route mat. Trash a card from your hand.   Setup: Put a token on each Victory card Supply pile. When a card is gained from that pile, move the token to the Trade Route mat.,,,,,,")); TradeRoute.FixName();
    Trader.Set(QString("Trader"),QString("Hinterlands"),QString("$4"),QString("Action - Reaction"),QString("Trash a card from your hand. Gain a number of Silvers equal to its cost in Coins.   When you would gain a card, you may reveal this from your hand. If you do, instead, gain a silver.,,,,,,")); Trader.FixName();
    TradingPost.Set(QString("TradingPost"),QString("Intrigue"),QString("$5"),QString("Action"),QString("Trash 2 cards from your hand. If you do")); TradingPost.FixName();
    Transmute.Set(QString("Transmute"),QString("Alchemy"),QString("$0 1P"),QString("Action"),QString("Trash a card from your hand. If it is an... Action card, gain a Duchy Treasure card, gain a Transmute Victory card, gain a Gold,,,,,,")); Transmute.FixName();
    TreasureMap.Set(QString("TreasureMap"),QString("Seaside"),QString("$4"),QString("Action"),QString("Trash this and another copy of Treasure Map from your hand. If you do trash two Treasure Maps")); TreasureMap.FixName();
    Treasury.Set(QString("Treasury"),QString("Seaside"),QString("$5"),QString("Action"),QString("+1 Card")); Treasury.FixName();
    Tribute.Set(QString("Tribute"),QString("Intrigue"),QString("$5"),QString("Action"),QString("The player to your left reveals then discards the top 2 cards of his deck. For each differently named card revealed")); Tribute.FixName();
    TrustySteed.Set(QString("TrustySteed"),QString("Cornucopia"),QString("$0"),QString("Action - Prize"),QString("Choose two: +2 Cards; +2 Actions; +2 Coins; gain 4 Silvers and put your deck into your discard pile. (The choices must be different)  (This is not in the Supply.),,,,,,")); TrustySteed.FixName();
    Tunnel.Set(QString("Tunnel"),QString("Hinterlands"),QString("$3"),QString("Victory - Reaction"),QString("2 VP [large shield]   When you discard this other than during a Clean-up phase, you may reveal it. If you do, gain a Gold.,,,,,,")); Tunnel.FixName();
    University.Set(QString("University"),QString("Alchemy"),QString("$2 1P"),QString("Action"),QString("+2 Actions You may gain an Action card costing up to 5 Coins.,,,,,,")); University.FixName();
    Upgrade.Set(QString("Upgrade"),QString("Intrigue"),QString("$5"),QString("Action"),QString("+1 Card")); Upgrade.FixName();
    Urchin.Set(QString("Urchin"),QString("Dark Ages"),QString("$3"),QString("Action - Attack"),QString("+1 Card, +1 Action Each other player discards down to 4 cards in hand.   When you play another Attack card with this in play, you may trash this. If you do, gain a mercenary from the Mercenary pile.,,,,,,")); Urchin.FixName();
    Vagrant.Set(QString("Vagrant"),QString("Dark Ages"),QString("$2"),QString("Action"),QString("+1 Card, +1 Action Reveal the top card of your deck. If it's a Curse, Ruins, Shelter, or Victory card, put it into your hand.,,,,,,")); Vagrant.FixName();
    Vault.Set(QString("Vault"),QString("Prosperity"),QString("$5"),QString("Action"),QString("+2 Cards Discard any number of cards. +1 Coin per card discarded. Each other player may discard 2 cards. If he does, he draws a card.,,,,,,")); Vault.FixName();
    Venture.Set(QString("Venture"),QString("Prosperity"),QString("$5"),QString("Treasure"),QString("Worth 1 Coin. When you play this, reveal cards from your deck until you reveal a Treasure. Discard the other cards. Play that Treasure.,,,,,,")); Venture.FixName();
    Village.Set(QString("Village"),QString("Base"),QString("$3"),QString("Action"),QString("+1 Card")); Village.FixName();
    Vineyard.Set(QString("Vineyard"),QString("Alchemy"),QString("$0 1P"),QString("Victory"),QString("Worth 1 Victory for every 3 Action cards in your deck (rounded down).,,,,,,")); Vineyard.FixName();
    WalledVillage.Set(QString("WalledVillage"),QString("Promo"),QString("$4"),QString("Action"),QString("+1 Card +2 Actions   At the start of Clean-up, if you have this and no more than one other Action card in play, you may put this on top of your deck.,,,,,,")); WalledVillage.FixName();
    WanderingMinstrel.Set(QString("WanderingMinstrel"),QString("Dark Ages"),QString("$4"),QString("Action"),QString("+1 Card, +2 Actions Reveal the top 3 cards of your deck. Put the Actions back on top in any order and discard the rest.,,,,,,")); WanderingMinstrel.FixName();
    Warehouse.Set(QString("Warehouse"),QString("Seaside"),QString("$3"),QString("Action"),QString("+3 Card")); Warehouse.FixName();
    Watchtower.Set(QString("Watchtower"),QString("Prosperity"),QString("$3"),QString("Reaction"),QString("Draw until you have 6 cards in hand.   When you gain a card, you may reveal this from your hand. If you do, either trash that card, or put it on top of your deck.,,,,,,")); Watchtower.FixName();
    Wharf.Set(QString("Wharf"),QString("Seaside"),QString("$5"),QString("Action - Duration"),QString("Now and at the start of your next turn: +2 Cards")); Wharf.FixName();
    WishingWell.Set(QString("WishingWell"),QString("Intrigue"),QString("$3"),QString("Action"),QString("+1 Card")); WishingWell.FixName();
    Witch.Set(QString("Witch"),QString("Base"),QString("$5"),QString("Action - Attack"),QString("+2 Cards")); Witch.FixName();
    Woodcutter.Set(QString("Woodcutter"),QString("Base"),QString("$3"),QString("Action"),QString("+1 Buy")); Woodcutter.FixName();
    WorkersVillage.Set(QString("WorkersVillage"),QString("Prosperity"),QString("$4"),QString("Action"),QString("+1 Card +2 Actions +1 Buy,,,,,,")); WorkersVillage.FixName();
    Workshop.Set(QString("Workshop"),QString("Base"),QString("$3"),QString("Action"),QString("Gain a card costing up to 4 Coins.,,,,,,")); Workshop.FixName();
    YoungWitch.Set(QString("YoungWitch"),QString("Cornucopia"),QString("$4"),QString("Action - Attack"),QString("+2 Cards  Discard 2 cards. Each other player may reveal a Bane card from his hand. If he doesn’t, he gains a Curse.   Setup: Add an extra Kingdom card pile costing 2 Coins or 3 Coins to the Supply. Cards from that pile are Bane cards.,,,,,,")); YoungWitch.FixName();
}
